[package]
name = "listeria"
version = "0.1.1"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
regex = "^1"
lazy_static = "^1"
chrono = "*"
config = "*"
serde_json = "^1"
urlencoding = "^1"
roxmltree = "*"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
tokio = { version = "^1", features = ["full","rt-multi-thread"] }
futures = "*"
mysql_async = "*"
md5 = "*"
pickledb = "*"
tempfile = "*"
